### ISSUE TITLE
Maximum filesize reached

### ISSUE THREAD

**Issue by anatolii-t** [elivin/shutter-sftp#2]
Hi.
When i upload file i get an error:
https://cdn1.radikalno.ru/uploads/2019/5/23/745fbe0acd89cfac4c908fb8d1359c2f-full.png

It does not matter what filesize. I try upload file with size 1,2 Kb and still got this error.

I think problem is not in plugin. Can you help me solve this problem?

**Comment by elivin** [comment]
Hi.
Do you have a fingerprint for host in known_hosts?
Try to connect by ssh. If you don't have a fingerprint, ssh client will add it to know_hosts:
http://files.nihilis1.myihor.ru/screen/adding_fingerprint.png

**Comment by anatolii-t** [comment]
Thanks for reply.
Yes, i have already connect  to neaded server and have fingerprint.
But i try to connect with key that have passphrase. Maybe problem with it?

**Comment by elivin** [comment]
You need to add passphrase to `.config/shutter-sftp.json`. This is the only way now.

**Comment by anatolii-t** [comment]
The passphrase already in config. But no result.

**Comment by elivin** [comment]
I fixed error messages. But they are still useless))
Try to update plugin file and restart shutter.

**Comment by anatolii-t** [comment]
Thank you.
Now i have this error:
"Error: SSH slave exited unexpectedly with error code 255"

Maybe i can turn on debugging mode, for find the cause?

**Comment by elivin** [comment]
Debugging mode is enabled. Run shutter in terminal:
http://files.nihilis1.myihor.ru/screen/shutter_ssh_log.png

**Comment by anatolii-t** [comment]
![33a9314fd](https://user-images.githubusercontent.com/33239086/58372345-79c4c680-7f24-11e9-8ee3-d13a5dcbff7c.jpg)

I think my main error is:
Permission denied (publickey,gssapi-with-mic,password).

I suppose problem with pair key / passphrase?

**Comment by elivin** [comment]
> debug1: Next authentication method: publickey
> debug1: Offering RSA public key: /home/anatoliy/.ssh/id_rsa
> debug1: Authentications that can continue: publickey,gssapi-with-mic,password

Do you use `~/.ssh/id_rsa`? It looks like sftp module ignore `key_path` option.

**Comment by elivin** [comment]
Checked this case, `key_path` option is working correctly.
I found command that run sftp module. You can run it for check (without `-s sftp`)
![net_sftp_cmd](https://user-images.githubusercontent.com/12787111/58373257-8bb66180-7f44-11e9-9c22-b2a9a6dafa80.png)

**Comment by anatolii-t** [comment]
I use absolute path in config.
This is ssh verbose output when i manually connect:
```
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/anatoliy/.ssh/id_rsa
debug1: Authentications that can continue: publickey,gssapi-with-mic,password
debug1: Offering RSA public key: username@machine
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug1: Authentication succeeded (publickey).
```

May be problem with 
`debug1: Offering RSA public key: username@machine`
and perl dose not do this action/
because key created on other computer with other username.

**Comment by elivin** [comment]
Perl run ssh client. And print command to console with prefix `ssh cmd:`

> debug1: Offering RSA public key: username@machine

Is this file? Server accepted this "key". Try to load your screen without `key` option in `.config/shutter-sftp.json`

**Comment by anatolii-t** [comment]
I'm sorry.
I have used wrong key))
When i change pass to correct key plugin start work)
Thanks for your help.
